### ISSUE TITLE
BigTest Alpha

### ISSUE THREAD

**Issue by cowboyd** [thefrontside/bigtest#142]
Now that we have an implementation and architecture forming, it's time to laser focus our requirements towards the smallest possible usable system; one that puts together all of the pieces that we currently have lying on the workshop floor. This issue lays out the experience of the MVP, and references the remaining work needed to implement that experience.

### Implementation

This section is currently more of a brain dump, but will involve links to other issues eventually.

- [x] Convert command server to GraphQL endpoint https://github.com/bigtestjs/server/issues/29 **PR ->**  thefrontside/server#34 
- [x] Implement `browsers` query (bigtestjs/server/issues/33)
- [x] Define and implement `@bigtest/interactor` 2.0 API https://github.com/bigtestjs/server/issues/35
- [x] Define and implement `@bigtest/suite` format for declaring test suites https://github.com/bigtestjs/server/issues/30
- [x] Bundle test suite into entry point that can be consumed by harness thefrontside/server#31  **PRs ->** bigtestjs/server/pull/51 bigtestjs/server/pull/66 bigtestjs/server/pull/101
- [x] Run test suite using harness (bigtestjs/server/issues/32)
- [x] Make a distributable package (bigtestjs/server/issues/39)
  - [x] Optionally have orchestrator serve agent application from pre-compiled assets (bigtestjs/server/issues/44)
  - [x] Optionally have orchestrator server test harness javascript from pre-compiled assets (bigtestjs/server/issues/43)
- [x] Orchestrator can start the application under test (bigtestjs/server/issues/40)
  - [x] Add fixture app for development (bigtestjs/server/issues/41)
- [x] Automatically launch agent from orchestrator based on orchestrator configuration (#233)
- [ ] Command Line Interface
  - [ ] `init` command to set up a bigtest project completed default agent, default app command, and default app port (#156)
  - [x] `run` command do a single-shot test run for CI on a single agent
  - [ ] create global`bigtest` shim that looks for the current project and uses `@bigtest/cli`, also so that `npx bigtest init` can work.
### Experience

We want to drive as close to the usage of bigtest as it will actually happen in the wild. That means being able to drop it into middle of an existing project, and start writing tests against that project immediately. To simulate that experience, we'll use `create-react-app` to generate a `TodoMVC` implementation and then run the todo mvc test suite against it implemented as a BigTest suite.

So, given that we have this existing TodoMVC app, we should be able to execute the following commands:

```
# add bigtest to the project
$ yarn add -D @bigtest/server
```

Now, we can write our tests in `bigtest/**/*.test.ts` files. For our example application, we'll have a `todomvc.test.ts` file that contains the [TodoMVC test suite][1] expressed as as BigTest suite.

With our application in hand, and the test suite to boot, we'll fire up the BigTest server:

```
$ yarn bigtestd --app http://localhost:3000 --start-with 'yarn start'
bigtest server v1.5.6
[info] - connect browsers to http://localhost:24000
[info] - run commands at http://localhost:24001
[info] - 25 tests found in `~/project/todomvc/bigtest`
```

The `--app` parameter is the url where the application under test is going to be served by its own build system and the `--start-with` parameter is the command to run to start the application at that url. It's by completely abstracting the application behind `http` like this that BigTest is able to completely avoid any special hooking into the build system. The test files will be built and maintained completely separately.

Let's look at the output: `bigtestd` will automatically find the tests living in `bigtest/todomvc.test.ts`, build them automatically with typescript, and be able to get basic metadata about it like how many tests there are. 

> Note that TypeScript support is optional, but that we'll be using it in our example just so that it can be shown to be done.

The other thing it will do is print out the port to which browsers that we want to test can be connected. We can connect any number of browsers this way just by pointing them att `http://localhost:24000` For our MVP we're going to require that browsers be connected manually, but eventually we'll have commands to launch them automatically as part of the test suite.

```
$ open -a Safari http://localhost:24000
```

This will point the `Safari` browser against our proxy server which will load the agent, the harness, and pull the test suite into the harness. Now it is a connected browser, and we can issue commands that involve it. Which is a convenient segue into our _command server_. The other thing that got echoed to the console when we started `bigtestd` was the url where it can accept commands: `http://localhost:24001`. When you navigate your browser to this url, you'll come to an instance of [GraphiQL][2] where you can query the state of the bigtest server, or you can issue commands. In our case, we could issue a query to get the name of all the browsers currently connected:

```GraphQL
browsers {
  name
  status
}
```

resolves to

```json
{
  "browsers": [{
    "name": "Safari",
    "status": "ready"
  }]
}
```

Or to get metadata about the test suite:

```GraphQL
suite {
  length
  tests {
    context {
      description
    }
    description
  }
}
```

might return something like:
```json
{
  "suite": {
    "length": 25,
    "tests": [{
      "context": {
        "description": "New Todo",
      },
      "description": "clears the input field when item is added"
    }]
  }
}
```

Now that we have a connected browser, we can actually create a trial with it:

```GraphQL
run(browser: "Safari") {
  id
  status
  passed {
    length
  }
  failed {
    length
  }
}
```

This runs the test suite against the `"Safari"` browser and collects results at the `Trial` object referenced by `id`:

```json
{
  "run": {
    "id": "Safari/1",
    "status": "running",
    "passed": {
      "length": 0
    },
    "failed": {
      "length": 0
     }
  }
}
```
And we can now query for this trial directly now that we have the id:

```GraphQL
trials(id: "Safari/1") {
  status
  passed {
    length
  }
  failed {
    length
  }  
}
```

which we can use to post updates to anywhere:

```json
{
  "trial": {
    "status": "complete",
    "passed": {
      "length": 24
    },
    "failed": {
      "length": 1
     }
  }
}

```

[1]: https://github.com/kt3k/todomvc-test/blob/master/test.js
[2]: https://github.com/graphql/graphiql

**Comment by cowboyd** [comment]
Completed. See [Beta milestone](https://github.com/thefrontside/bigtest/milestone/2) for continuation.
