### ISSUE TITLE
Quest: Define and implement new interactor syntax

### ISSUE THREAD

**Issue by cowboyd** [thefrontside/bigtest#146]
Part of thefrontside/bigtest#142 

After two years of learning, it's time to re-think the interactor API to be more intuitive based on users' existing knowledge of the DOM and the principles of component oriented design.

To do this we'll model it as a queryable, continuous graph of strongly typed relationships rather than an object instance created out of thin air (every interactor is ultimately traceable to the root) Ultimately this will be more understandable and ultimately more composable.

Get all the button on the page:

```js

import { Button } from `@bigtest/interactor`;

let buttons = Button.all(); //=> Iterable<Button>

let first = buttons.first();
```

```js
class Form extends Interactor {
  cancel = Button.first();
  submit = Button.last();

  input = TextField.first('[data-test-input]');

  errors = Validation.
      .where('[data-validation-error]')
      .where(':visible');
}
```

In this way, it takes on the characteristics of a `Link` relationship or an `ActiveRecord` relationship (for those familiar with those technologies).

These query methods do  not actually look up the button when the method is called, it only defines the relationship of the button to the structure of the document or sub-document. For example, the only time that the DOM is actually queried for existence of the button would be at the time an action method like`click()` is invoked. Even in that situtation however, the actions will be convergent which means that they will perform themselves whenever the button becomes available, and not fail if they aren't at the exact moment that the action is invoked)

This is only a straw man proposal, and definition of the Interactor syntax is part of the scope of this issue

### Action items

- [ ] Enumerate difficulties with current API (https://github.com/bigtestjs/interactor/issues/74)
- [ ] Draft new API using type declarations (https://github.com/bigtestjs/interactor/issues/75)
- [ ] Set up repo for new TypeScript codebase (https://github.com/bigtestjs/interactor/issues/76)
- [ ] Set up test harness for new TypeScript codebase (https://github.com/bigtestjs/interactor/issues/77)
- [ ] Implement new API (https://github.com/bigtestjs/interactor/issues/78)

**Comment by cowboyd** [comment]
I'm going to mark this as resolved since we now have working prototypes of the new interactors and it's more iteration than research at this point.
