### ISSUE TITLE
Clean up @bigtestjs

### ISSUE THREAD

**Issue by minkimcello** [thefrontside/bigtest#390]
## Motivation
We deprecated `@bigtest/convergence` and moved most of the packages over to `@thefrontside/bigtest` but there are still packages in the old organization that has not yet been tidied up. This issue is to keep track of what needs to be done in order to tie up loose ends in the old organization.

## Approach
Below are the list of packages in both organizations:
![Group](https://user-images.githubusercontent.com/29791650/86626234-680d7980-bf94-11ea-8866-208c33f3b2a3.png)
_Packages that aren't scoped to bigtest (e.g. websites or todomvc) aren't included on this list._

The packages highlighted in blue are the ones that were transferred over to the new monorepo on `@thefrontside` and the packages highlighted in yellow are the ones that we will be focusing on:
- `@bigtest/convergence`: Deprecated
- `@bigtest/meta`: Was never published
- `@bigtest/mirage`: Not deprecated yet
- `@bigtest/mocha`: Not deprecated yet
- `@bigtest/react`: Not deprecated yet

## TODOs
- [x] To make these changes I think I need to be added to the bigtestjs organization. Should I log in as jack and add myself?
- [x] Un-archive all repositories on `@bigtestjs` so that we can update each of their READMEs with a message saying "Bigtest has moved over to `@thefrontside/bigtest, please join us there` at the top (or something along those lines).
  - Once the updated READMEs are pushed, we can re-archive the repositories.
- [x] Update all bigtestjs repos' descriptions/website-urls
- [x] Updated organization description to direct users to this monorepo
- [ ] Deprecate `mirage`, `mocha`, `react` with custom message.
  - Leaving out `meta` because it was never published to begin with.
  - We can un-deprecate and re-deprecate `convergence` with a deprecation message that directs users to check out the new bigtest monorepo on `@thefrontside`.

**Comment by cowboyd** [comment]
> Should I log in as jack and add myself?

@minkimcello since nobody else has the ability to log into that org, I think that's our only available options.

**Comment by minkimcello** [comment]
@cowboyd I'm having difficulty logging in because of the 6 digit verification code. Should we setup 2FA for Jack's Github account?

**Comment by minkimcello** [comment]
@cowboyd So I'll go ahead and unarchive all repositories and push the deprecated README. It would look something like this:

<img width="715" alt="Screen Shot 2020-07-14 at 10 55 11 AM" src="https://user-images.githubusercontent.com/29791650/87441106-b63c0180-c5c0-11ea-8959-6a316fbfa9fb.png">

Does that look okay?

And for the deprecation message on npmjs, I will undeprecate `convergence` and redeprecate it along with `mirage`, `mocha`, and `react`. (And skip `meta` because it was never published). What should we use for the deprecated message?

<img width="613" alt="Screen Shot 2020-07-14 at 10 55 56 AM" src="https://user-images.githubusercontent.com/29791650/87441355-01eeab00-c5c1-11ea-9ea1-df4a832d3b6d.png">

**Comment by cowboyd** [comment]
Looks good, although I'm wondering if we can't entice folks on the fence with a happier and more context-providing message?

Something like. "In order to make bigtest development faster and friction free, we've consolidated all our individual projects into a single repository on the Frontside Organization. We'd love to see you there!"

Can we also add updated links in the npm deprecation message?

**Comment by minkimcello** [comment]
Like this?

<img width="816" alt="Screen Shot 2020-07-14 at 11 06 22 AM" src="https://user-images.githubusercontent.com/29791650/87442248-0f586500-c5c2-11ea-932b-54f6b9744231.png">

And i'm looking into what it looks like if the npm deprecate message has a link. It'll show up as a string on npmjs.org but i'm wondering if it'll be clickable in vscode.

**Comment by minkimcello** [comment]
Yeah they're not clickable.

![Screen Shot 2020-07-14 at 11 15 19 AM](https://user-images.githubusercontent.com/29791650/87443307-52ff9e80-c5c3-11ea-8154-fdc19686f932.png)

**Comment by minkimcello** [comment]
And should I also update all the repo descriptions as jonas did for `@bigtestjs/server`?

What server's description looks like now:
<img width="548" alt="Screen Shot 2020-07-14 at 11 23 44 AM" src="https://user-images.githubusercontent.com/29791650/87444234-84c53500-c5c4-11ea-96b3-39273ac0ee09.png">

<img width="310" alt="Screen Shot 2020-07-14 at 11 22 15 AM" src="https://user-images.githubusercontent.com/29791650/87444130-63644900-c5c4-11ea-84db-ebc213a2cefc.png">

What I can change all of the projects' description to:
<img width="303" alt="Screen Shot 2020-07-14 at 11 22 33 AM" src="https://user-images.githubusercontent.com/29791650/87444169-6e1ede00-c5c4-11ea-97db-aa6830e3d000.png">

(Made the message a little shorter and easier to read than what we would have in the readme)

**Comment by cowboyd** [comment]
Yes, definitely update descriptions. 

One final thing. Let's hold off deprecating public packages until we have a public, non-beta replacement for them.

**Comment by cowboyd** [comment]
That message looks great. Can you include "single repository" in the hyperlink?

**Comment by minkimcello** [comment]
oh okay i'll go ahead with the repo changes for now and do the npm stuff later then.

**Comment by minkimcello** [comment]
what do you mean by single repository?

**Comment by minkimcello** [comment]
oh like this:

# Dep ⭐ 
In order to make bigtest development faster and friction free, we've consolidated all our individual projects into a [single repository on the Frontside Organization](github.com). We'd love to see you there!

**Comment by cowboyd** [comment]
@minkimcello I think you're all done here, no?

**Comment by minkimcello** [comment]
@cowboyd Should we leave it up until we `npm deprecate "new message"` the remaining packages?

**Comment by cowboyd** [comment]
Nah, let's close this out. We can kick that can down the road since it's still a ways out. We can create a separate issue post MVP? Nice work!
